gcc my_stream_client.c -o my_stream_client \
      -I"C:\OpenCV\cxcore\include" \
      -I"C:\OpenCV\cv\include" \
      -I"C:\OpenCV\otherlibs\highgui" \
      -L"C:\OpenCV\lib" -lcxcore -lcv -lhighgui -lpthread -lwsock32